total_iters: 1
output_dir: output_dir
checkpoints_dir: checkpoints

model:
  name: AOTGANModel
  generator:
    name: InpaintGenerator
    rates: [1, 2, 4, 8]
    block_num: 8
  discriminator:
    name: Discriminator
    inc: 3
  criterion:
    name: AOTGANCriterionLoss
    pretrained: https://paddlegan.bj.bcebos.com/models/vgg19feats.pdparams
  l1_weight: 1
  perceptual_weight: 1
  style_weight: 250
  adversal_weight: 0.01
  img_size: 512

dataset:
  train:
    name: AOTGANDataset
    dataset_path: test/aotgan
    img_size: 512
  test:
    name: AOTGANDataset_test
    dataset_path: test/aotgan
    img_size: 512

lr_scheduler: # abundoned
  name: LinearDecay
  learning_rate: 0.0001
  start_epoch: 99999
  decay_epochs: 99999
  # will get from real dataset
  iters_per_epoch: 1

optimizer:
  lr: 0.0001
  optimG:
    name: Adam
    net_names:
      - net_gen
    beta1: 0.5
    beta2: 0.999
  optimD:
    name: Adam
    net_names:
      - net_des
    beta1: 0.5
    beta2: 0.999

log_config:
  interval: 1
  visiual_interval: 1

snapshot_config:
  interval: 1

predict:
  name: AOTGANGenerator
  rates: [1, 2, 4, 8]
  block_num: 8
  img_size: 512
