epochs: 200
output_dir: output_dir

model:
  name: FirstOrderModel
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: True
  generator:
    name: FirstOrderGenerator
    kp_detector_cfg:
      temperature: 0.1
      block_expansion: 32
      max_features: 1024
      scale_factor: 0.25
      num_blocks: 5
      single_jacobian_map: True
    generator_cfg:
      block_expansion: 64
      max_features: 512
      num_down_blocks: 2
      num_bottleneck_blocks: 6
      estimate_occlusion_map: True
      dense_motion_params:
        block_expansion: 64
        max_features: 1024
        num_blocks: 5
        scale_factor: 0.25
  discriminator:
    name: FirstOrder_Discriminator
    discriminator_cfg:
      scales: [1]
      block_expansion: 32
      max_features: 512
      num_blocks: 4
      sn: True
#  gan_mode: vanilla #  Loss较难分离，不使用gan_mode参数设置

train_params:
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 100
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 1
    discriminator_gan: 1
    feature_matching: [10, 10, 10, 10]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 10
    equivariance_jacobian: 10

optimizer:
  name: Adam

lr_scheduler:
  epoch_milestones: [60, 90]
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  lr_kp_detector: 2.0e-4

dataset:
  train:
    name: FirstOrderDataset
    phase: train
    # 数据集路径，请保证该目录下有train和test两个子文件夹，并将数据与对应置入
    dataroot: /home/aistudio/work/dataset/moving-gif
    num_repeats: 10
    id_sampling: False
    pairs_list: None
    frame_shape: [ 256, 256, 3 ]
    process_time: False
    create_frames_folder: True
    num_workers: 4
    batch_size: 1
    max_dataset_size: inf
    direction: BtoA
    input_nc: 3
    output_nc: 3
    serial_batches: False
    pool_size: 0
# TODO:
#    augmentation_params:
#      flip_param:
#        horizontal_flip: True
#        time_flip: True
#      crop_param:
#        size: [ 256, 256 ]
#      resize_param:
#        ratio: [ 0.9, 1.1 ]
#      jitter_param:
#        hue: 0.5
#    transforms:
#      - name: Resize
#        size: [286, 286]
#        interpolation: 'bicubic' #cv2.INTER_CUBIC
#        keys: [image, image]
#      - name: PairedRandomCrop
#        size: [256, 256]
#        keys: [image, image]
#      - name: PairedRandomHorizontalFlip
#        prob: 0.5
#        keys: [image, image]
#      - name: Transpose
#        keys: [image, image]
#      - name: Normalize
#        mean: [127.5, 127.5, 127.5]
#        std: [127.5, 127.5, 127.5]
#        keys: [image, image]
#  test:
#    name: PairedDataset
#    dataroot: data/cityscapes/
#    phase: test
#    max_dataset_size: inf
#    direction: BtoA
#    input_nc: 3
#    output_nc: 3
#    serial_batches: True
#    pool_size: 50
#    transforms:
#      - name: Resize
#        size: [256, 256]
#        interpolation: 'bicubic' #cv2.INTER_CUBIC
#        keys: [image, image]
#      - name: Transpose
#        keys: [image, image]
#      - name: Normalize
#        mean: [127.5, 127.5, 127.5]
#        std: [127.5, 127.5, 127.5]
#        keys: [image, image]

log_config:
  interval: 100
  visiual_interval: 500

snapshot_config:
  interval: 5