total_iters: 30000
output_dir: output_dir
checkpoints_dir: checkpoints
# min_max:
#   (0., 1.)

model:
  name: PhotoPenModel
  generator:
    name: SPADEGenerator
    ngf: 24
    num_upsampling_layers: normal
    crop_size: 256
    aspect_ratio: 1.0
    norm_G: spectralspadebatch3x3
    semantic_nc: 14
    use_vae: False
    nef: 16
  discriminator:
    name: MultiscaleDiscriminator
    ndf: 128
    num_D: 4
    crop_size: 256
    label_nc: 12
    output_nc: 3
    contain_dontcare_label: True
    no_instance: False
    n_layers_D: 6
  criterion:
    name: VGG19


dataset:
  train:
    name: PhotoPenDataset
    content_root: test/coco_stuff
    load_size: 286
    crop_size: 256
    num_workers: 0
    batch_size: 1
  test:
    name: PhotoPenDataset
    content_root: data/coco/test2017/
    style_root: data/starrynew.png
    load_size: 128
    crop_size: 128
    num_workers: 0
    batch_size: 1

lr_scheduler:
  name: NonLinearDecay
  learning_rate: 1e-4
  lr_decay: 5e-5

optimizer:
  optimG:
    name: Adam
    net_names:
      - net_dec
    beta1: 0.9
    beta2: 0.999

validate:
  interval: 500
  save_img: false

log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 5000

predict:
  name: SPADEGenerator
  ngf: 24
  num_upsampling_layers: normal
  crop_size: 256
  aspect_ratio: 1.0
  norm_G: spectralspadebatch3x3
  semantic_nc: 14
  use_vae: False
  nef: 16
  contain_dontcare_label: True
  label_nc: 12
  batchSize: 1
 