epochs: 200
output_dir: output_dir
lambda_L1: 100

model:
  name: Pix2PixModel
  generator:
    name: UnetGenerator
    norm_type: batch
    input_nc: 3
    output_nc: 3
    num_downs: 8 #unet256
    ngf: 64
    use_dropout: False
  discriminator:
    name: NLayerDiscriminator
    ndf: 64
    n_layers: 3
    input_nc: 6
    norm_type: batch
  gan_mode: vanilla

dataset:
  train:
    name: PairedDataset
    dataroot: data/facades/
    num_workers: 0
    batch_size: 1
    phase: train
    max_dataset_size: inf
    direction: BtoA
    input_nc: 3
    output_nc: 3
    serial_batches: False
    pool_size: 0
    transforms:
      - name: Resize
        size: [286, 286]
        interpolation: 'bicubic' #cv2.INTER_CUBIC
        keys: [image, image]
      - name: PairedRandomCrop
        size: [256, 256]
        keys: [image, image]
      - name: PairedRandomHorizontalFlip
        prob: 0.5
        keys: [image, image]
      - name: Transpose
        keys: [image, image]
      - name: Normalize
        mean: [127.5, 127.5, 127.5]
        std: [127.5, 127.5, 127.5]
        keys: [image, image]
  test:
    name: PairedDataset
    dataroot: data/facades/
    phase: test
    max_dataset_size: inf
    direction: BtoA
    input_nc: 3
    output_nc: 3
    serial_batches: True
    pool_size: 50
    transforms:
      - name: Resize
        size: [256, 256]
        interpolation: 'bicubic' #cv2.INTER_CUBIC
        keys: [image, image]
      - name: Transpose
        keys: [image, image]
      - name: Normalize
        mean: [127.5, 127.5, 127.5]
        std: [127.5, 127.5, 127.5]
        keys: [image, image]

optimizer:
  name: Adam
  beta1: 0.5

lr_scheduler:
  name: linear
  learning_rate: 0.0002
  start_epoch: 100
  decay_epochs: 100

log_config:
  interval: 100
  visiual_interval: 500

snapshot_config:
  interval: 5
