epochs: 300
output_dir: output_dir
adv_weight: 1.0
cycle_weight: 10.0
identity_weight: 10.0
cam_weight: 1000.0

model:
  name: UGATITModel
  generator:
    name: ResnetUGATITGenerator
    input_nc: 3
    output_nc: 3
    ngf: 64
    n_blocks: 4
    img_size: 256
    light: True
  discriminator_g:
    name: UGATITDiscriminator
    input_nc: 3
    ndf: 64
    n_layers: 7
  discriminator_l:
    name: UGATITDiscriminator
    input_nc: 3
    ndf: 64
    n_layers: 5

dataset:
  train:
    name: UnpairedDataset
    dataroot: data/selfie2anime
    num_workers: 0
    phase: train
    max_dataset_size: inf
    direction: AtoB
    input_nc: 3
    output_nc: 3
    serial_batches: False
    transforms:
      - name: Resize
        size: [286, 286]
        interpolation: 'bilinear' #'bicubic' #cv2.INTER_CUBIC
      - name: RandomCrop
        size: [256, 256]
      - name: RandomHorizontalFlip
        prob: 0.5
      - name: Transpose
      - name: Normalize
        mean: [127.5, 127.5, 127.5]
        std: [127.5, 127.5, 127.5]
  test:
    name: SingleDataset
    dataroot: data/selfie2anime/testA
    max_dataset_size: inf
    direction: AtoB
    input_nc: 3
    output_nc: 3
    serial_batches: False
    transforms:
      - name: Resize
        size: [256, 256]
        interpolation: 'bilinear' #cv2.INTER_CUBIC
      - name: Transpose
      - name: Normalize
        mean: [127.5, 127.5, 127.5]
        std: [127.5, 127.5, 127.5]

optimizer:
  name: Adam
  beta1: 0.5
  weight_decay: 0.0001

lr_scheduler:
  name: linear
  learning_rate: 0.0001
  start_epoch: 150
  decay_epochs: 150

log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 30
