total_iters: 200000000
output_dir: /workspace_data/hq
checkpoints_dir: checkpoints
eval_interval: 3000
save_optimizer_state: True

disc_initial_learning_rate: 1e-4


model:
  name: Wav2LipModelHq
  syncnet_wt: 0.
  disc_wt: 0.07
  generator:
    name: Wav2Lip
  discriminator_sync:
    name: SyncNetColor
  discriminator_hq:
    name: Wav2LipDiscQual

dataset:
  train:
    name: Wav2LipDataset
    dataroot: /workspace_data/lrs2_preprocessed
    filelists_path: /workspace/PaddleGAN
    img_size: 96
    split: train
    batch_size: 8
    num_workers: 0
  test:
    name: Wav2LipDataset
    dataroot: /workspace_data/lrs2_preprocessed
    filelists_path: /workspace/PaddleGAN
    img_size: 96
    split: val
    batch_size: 16
    num_workers: 0

optimizer:
  optimizer_G:
    name: Adam
    net_names:
      - netG
    beta1: 0.5
  optimizer_DS:
    name: Adam
    net_names:
      - netDS
    beta1: 0.5
  optimizer_DH:
    name: Adam
    net_names:
      - netDH
    beta1: 0.5

validate:
  interval: 3000
  save_img: false

lr_scheduler:
  name: LinearDecay
  learning_rate: 0.0001
  start_epoch: 2000000
  decay_epochs: 2000000
  # will get from real dataset
  iters_per_epoch: 1

log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 3000
