epochs: 200
output_dir: tmp
checkpoints_dir: checkpoints
eval_interval: 3000
save_optimizer_state: True

syncnet_wt: 0.0
syncnet_batch_size: 64
syncnet_lr: 1e-4
syncnet_eval_interval: 10000
syncnet_checkpoint_interval: 10000

disc_wt: 0.07
disc_initial_learning_rate: 1e-4


model:
  name: Wav2LipModel
  generator:
    name: Wav2Lip
  discriminator:
    name: SyncNetColor

dataset:
  train:
    name: Wav2LipDataset
    dataroot: /workspace_data/lijianshe/lrs2_preprocessed
    filelists_path: /workspace/latest_ppgan/PaddleGAN
    img_size: 96
    split: train
    batch_size: 4
    num_workers: 4
  test:
    name: Wav2LipDataset
    dataroot: /workspace_data/lijianshe/lrs2_preprocessed
    filelists_path: /workspace/latest_ppgan/PaddleGAN
    img_size: 96
    split: val
    batch_size: 4
    num_workers: 4

optimizer:
  name: Adam


lr_scheduler:
  name: linear
  learning_rate: 0.0001
  start_epoch: 200
  decay_epochs: 200

log_config:
  interval: 10
  visiual_interval: 500

snapshot_config:
  interval: 1
